# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @keywords internal
pascal <- function(m, popsize, set) {
    .Call(`_RankedSetSampling_pascal`, m, popsize, set)
}

prod_c <- function(x) {
    .Call(`_RankedSetSampling_prod_c`, x)
}

secondmat <- function(firstorder, prods, popsize) {
    .Call(`_RankedSetSampling_secondmat`, firstorder, prods, popsize)
}

